config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :properties
  namespace :api do
    namespace :v1 do
      resources :properties
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  has_many_attached :images

  validates :name, presence: true, length: { in: 3..75 }

  def image_as_thumbnail
    images.map do |image|
      image.variant(resize_to_limit: [800, 800]).processed
    end
  end

  def display_as_thumbnail(image)
    image.variant(resize_to_limit: [800, 800]).processed
  end

  def cover_image
    @property.images[2]
  end
end

app/controllers/api/v1/properties_controller.rb
# frozen_string_literal: true

class Api::V1::PropertiesController < ApplicationController
  def get_image(images); end

  def index
    @properties = Property.all
    properties_render = @properties.map do |property|
      if property.images.attached?
        image_urls = property.images.map do |image|
          image = url_for(image)
        end
        property.as_json.merge(images: image_urls)
      else
        render json: property
      end
    end
    render json: properties_render
  end

  def show; end

  def new
    @property = Property.new
  end

  def edit; end

  def create
    @property = Property.create(property_params)
    if @property.save
      render json: @property, status: :created
    else
      render json: @property.errors, status: :unprocessable_entity
    end
  end

  def update
    if @property.update(property_params)
      render json: { message: 'Property Updated' }, status: :ok
    else
      render json: @property.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @property = Property.find(params[:id])
    if @property.destroy
      render json: { message: 'Property Removed' }, status: :ok
    else
      render json: @property.errors, status: :unprocessable_entity
    end
  end

  private

  def property_params
    params.require(:property).permit(:name, :city, :address, :bed, :bath, :size, :parking, :description, images: [])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::API
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  def index
    @properties = Property.all
  end

  def show; end

  def new
    @property = Property.new
  end

  def edit; end

  def create
    @property = Property.create(property_params)
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def property_params
    params.require(:property).permit(:name, :city, :address, :bed, :bath, :size, :parking, :description, images: [])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/properties_helper.rb
# frozen_string_literal: true

module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealstateApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/index.html.erb
<% @properties.each do |property| %>
  <div>
    <%= property.name %>
    </br>

    <% property.image_as_thumbnail.each do |image|%>
      <%= link_to image_tag(image), image %>
    <%end%>
    </br>

    <% property.images.each do |image|%>
      <%= link_to image_tag(property.display_as_thumbnail(image)), image %>
      </br>
    <%end%>
  </div>
<%end%>

app/views/properties/new.html.erb
<%= form_with model: @property, url: properties_path, local: true, method: :post do |form| %>
  <div>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.file_field :images, multiple: true %>
  </div>
  <div>
    <%= form.submit "Submit" %>
  </div>
<%end%>